# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartyNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartyNews
  pod 'SDWebImage', '~> 4.0'
  pod 'WBSegmentControl', '~> 0.2.0'
end
