# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftMemory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftMemory
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SDWebImage/WebP'
  pod 'ARCL'
end
